version: '3.7'

services:
  fastapi:
    env_file:
      - .env
    container_name: ${PROJECT:-backend}_fastapi
    depends_on:
      - db
    restart: always
    build: .
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    volumes:
      - ./backend:/backend
    networks:
      - bridge

  db:
    container_name: ${PROJECT:-backend}_db
    image: postgres:14-alpine3.16
    environment:
      - POSTGRES_DB=${DB_NAME:-backend_db}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    restart: always
    networks:
      - bridge

volumes:
  pgdata:

networks:
  bridge:
    driver: bridge